/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AiFieldGeneration {
	prompt?: string | null;
	field_type?: string | null;
	mapping?: string | null;
	translate_mapping?: boolean | null;
}
