/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AssetBlob {
	blob_type?: AssetBlob.BlobTypeEnum;
	name?: string | null;
	container?: string | null;
	size?: number | null;
	extension?: string | null;
	content_type?: string | null;
	md5?: string | null;
	add_data?: { [key: string]: any } | null;
	width?: number | null;
	height?: number | null;
	maxwidthheight?: number | null;
	quality?: number | null;
	orientation?: AssetBlob.OrientationEnum | null;
	colorspace?: string | null;
	profile?: string | null;
	transparency?: boolean | null;
	mode?: string | null;
	target?: string | null;
	filter?: string | null;
	dpi_x?: number | null;
	dpi_y?: number | null;
	perhash?: string | null;
	dominantcolor?: string | null;
	depth?: number | null;
	animated?: boolean | null;
	duration?: number | null;
	videocodec?: string | null;
	videobitrate?: number | null;
	fps?: number | null;
	colormode?: string | null;
	audiocodec?: string | null;
	audiosamplerate?: string | null;
	audiochanneloutput?: string | null;
	audiobitrate?: number | null;
	author?: string | null;
	title?: string | null;
	language?: string | null;
	wordcount?: number | null;
	pages?: number | null;
	encoding_name?: string | null;
	encoding_code?: string | null;
	url?: string | null;
	size_readable?: string | null;
	downloadable?: boolean | null;
	expires?: string | null;
	uploaded_date?: string | null;
	uploaded_by?: string | null;
}
export namespace AssetBlob {
	export const BlobTypeEnum = {
		Unknown: 'UNKNOWN',
		Image: 'IMAGE',
		Video: 'VIDEO',
		Audio: 'AUDIO',
		Document: 'DOCUMENT',
		Text: 'TEXT',
		Other: 'OTHER'
	} as const;
	export type BlobTypeEnum = (typeof BlobTypeEnum)[keyof typeof BlobTypeEnum];
	export const OrientationEnum = {
		Portrait: 'PORTRAIT',
		Landscape: 'LANDSCAPE',
		Square: 'SQUARE'
	} as const;
	export type OrientationEnum = (typeof OrientationEnum)[keyof typeof OrientationEnum];
}
