/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssistantChatMessage } from './assistantChatMessage.agravity';

export interface AssistantFeedbackRequest {
	rating?: string | null;
	messages?: Array<AssistantChatMessage> | null;
}
