/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AzureIdentity {
	id?: string | null;
	name?: string | null;
	description?: string | null;
	email?: string | null;
	ident_type?: AzureIdentity.IdentTypeEnum | null;
}
export namespace AzureIdentity {
	export const IdentTypeEnum = {
		User: 'USER',
		Group: 'GROUP',
		Apikey: 'APIKEY',
		Portal: 'PORTAL',
		Shared: 'SHARED'
	} as const;
	export type IdentTypeEnum = (typeof IdentTypeEnum)[keyof typeof IdentTypeEnum];
}
