/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CollTypeItem {
	id?: string | null;
	entity_type?: string | null;
	name?: string | null;
	item_type?: string | null;
	format?: string | null;
	label?: string | null;
	default_value?: any | null;
	mandatory?: boolean | null;
	searchable?: boolean | null;
	onlyasset?: boolean | null;
	multi?: boolean | null;
	md5?: string | null;
	group?: string | null;
	order?: number | null;
	translations?: { [key: string]: { [key: string]: any } } | null;
	status?: string | null;
	created_date?: string | null;
	created_by?: string | null;
	modified_date?: string | null;
	modified_by?: string | null;
	pk?: string | null;
	_etag?: string | null;
}
