/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionUDLReference } from './collectionUDLReference.agravity';
import { CollectionUDL } from './collectionUDL.agravity';

export interface CollectionUDLListEntity {
	id?: string | null;
	entity_type?: string | null;
	udl_refs?: Array<CollectionUDLReference> | null;
	udl_entries?: Array<CollectionUDL> | null;
	status?: string | null;
	created_date?: string | null;
	created_by?: string | null;
	modified_date?: string | null;
	modified_by?: string | null;
	pk?: string | null;
	_etag?: string | null;
}
