/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ExcelExportTableEntity {
	url?: string | null;
	status?: string | null;
	filters?: string | null;
	exclude?: string | null;
	ids?: string | null;
	language?: string | null;
	orchestration_id?: string | null;
	pk?: string | null;
	row_key?: string | null;
	timestamp?: string | null;
	eTag?: object;
}
