/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface HistoryEntry {
	id?: string | null;
	entity_type?: string | null;
	new_value?: object | null;
	old_value?: object | null;
	name?: HistoryEntry.NameEnum;
	status?: string | null;
	created_date?: string | null;
	created_by?: string | null;
	modified_date?: string | null;
	modified_by?: string | null;
	pk?: string | null;
	_etag?: string | null;
}
export namespace HistoryEntry {
	export type NameEnum = 'Created' | 'Updated' | 'Deleted' | 'Removed' | 'Published' | 'Unpublished' | 'Locked' | 'Unlocked' | 'Renewed' | 'Versioned' | 'DirtyMarked' | 'SystemUpgrade';
	export const NameEnum = {
		Created: 'Created' as NameEnum,
		Updated: 'Updated' as NameEnum,
		Deleted: 'Deleted' as NameEnum,
		Removed: 'Removed' as NameEnum,
		Published: 'Published' as NameEnum,
		Unpublished: 'Unpublished' as NameEnum,
		Locked: 'Locked' as NameEnum,
		Unlocked: 'Unlocked' as NameEnum,
		Renewed: 'Renewed' as NameEnum,
		Versioned: 'Versioned' as NameEnum,
		DirtyMarked: 'DirtyMarked' as NameEnum,
		SystemUpgrade: 'SystemUpgrade' as NameEnum
	};
}
