/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AzureIdentity } from './azureIdentity.agravity';

export interface PermissionSetting {
	id?: string | null;
	entity_type?: string | null;
	all_permissions?: Array<AzureIdentity> | null;
	status?: string | null;
	created_date?: string | null;
	created_by?: string | null;
	modified_date?: string | null;
	modified_by?: string | null;
	pk?: string | null;
	_etag?: string | null;
}
