/**
 * Agravity OpenAPI Documentation - Private Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReverseAssetSearchFieldSettings } from './reverseAssetSearchFieldSettings.agravity';

export interface SearchSettings {
	id?: string | null;
	entity_type?: string | null;
	vectorizable_ai_field_types?: Array<string> | null;
	similar_asset_search_ai_field_type_vector?: string | null;
	similar_asset_search_limit?: number | null;
	reverse_asset_search_ai_field?: ReverseAssetSearchFieldSettings | null;
	broadness?: { [key: string]: Array<string> } | null;
	status?: string | null;
	created_date?: string | null;
	created_by?: string | null;
	modified_date?: string | null;
	modified_by?: string | null;
	pk?: string | null;
	_etag?: string | null;
}
