/**
 * Agravity OpenAPI Documentation - Public Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Asset } from './asset.pub.agravity';
import { Collection } from './collection.pub.agravity';
import { PublishedAsset } from './publishedAsset.pub.agravity';

export interface AllWebAppData {
	root_collection?: Collection;
	subcollections?: Array<Collection> | null;
	assets?: Array<Asset> | null;
	pub_assets?: Array<PublishedAsset> | null;
	created_date?: string | null;
}
