/**
 * Agravity OpenAPI Documentation - Public Functions
 * <h1>Agravity API Reference</h1>This is the public API description of Agravity GmbH.<br/><h2>Resources</h2><ul> <li>Collection type management</li> <li>Collections management</li> <li>Assets management</li> <li>Assets operations</li> <li>Assets publishing</li> <li>Collection Sharing (consume share)</li> <li>Secure Upload (validate + upload file)</li> <li>Download ZIP</li> <li>Search</li> <li>General management</li></ul><h2> Operations</h2>Agravity API performs the following operations:<ul> <li>List / get single collection types</li> <li>List / get single collections</li> <li>List / get single  assets</li> <li>Operations on assets like: blobs, rotate, resize, similar, collections, customfields, download</li> <li>List / get single published asset</li> <li>Search for assets or collections</li> <li>Get version of deployment</li></ul><br/><b>API key is needed to access these endpoints.</b><br/><br/>Copyright © Agravity GmbH 2025. All Rights Reserved
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollTypeItem } from './collTypeItem.pub.agravity';

export interface Collection {
	id?: string | null;
	entity_type?: string | null;
	parent?: string | null;
	path?: string | null;
	level?: number | null;
	custom?: any | null;
	items?: Array<CollTypeItem> | null;
	translations?: { [key: string]: { [key: string]: object } } | null;
	role?: Collection.RoleEnum;
	name?: string | null;
	description?: string | null;
	add_properties?: { [key: string]: any } | null;
	status?: string | null;
	created_date?: string | null;
	created_by?: string | null;
	modified_date?: string | null;
	modified_by?: string | null;
	pk?: string | null;
	_etag?: string | null;
}
export namespace Collection {
	export type RoleEnum = 'NONE' | 'VIEWER' | 'EDITOR';
	export const RoleEnum = {
		None: 'NONE' as RoleEnum,
		Viewer: 'VIEWER' as RoleEnum,
		Editor: 'EDITOR' as RoleEnum
	};
}
