/**
 * Agravity OpenAPI Documentation - Public Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomClaimsProviderResponseClaims } from './customClaimsProviderResponseClaims.pub.agravity';

export interface CustomClaimsProviderResponseActionTokenIssuanceStart {
	claims?: CustomClaimsProviderResponseClaims | null;
	'@odata.type'?: string | null;
}
