/**
 * Agravity OpenAPI Documentation - Public Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomClaimsProviderResponseActionTokenIssuanceStart } from './customClaimsProviderResponseActionTokenIssuanceStart.pub.agravity';

export interface CustomClaimsProviderResponseDataTokenIssuanceStart {
	actions?: Array<CustomClaimsProviderResponseActionTokenIssuanceStart> | null;
	'@odata.type'?: string | null;
}
