/**
 * Agravity OpenAPI Documentation - Public Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PortalUserContext {
	key?: string | null;
	mandatory?: boolean | null;
	mapping?: { [key: string]: string } | null;
	options?: Array<string> | null;
}
