/**
 * Agravity OpenAPI Documentation - Public Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchAdminIndexerStatus } from './searchAdminIndexerStatus.pub.agravity';
import { SearchAdminSkillStatus } from './searchAdminSkillStatus.pub.agravity';
import { SearchAdminIndexStatus } from './searchAdminIndexStatus.pub.agravity';
import { SearchAdminDataSourceStatus } from './searchAdminDataSourceStatus.pub.agravity';

export interface SearchAdminStatus {
	index?: SearchAdminIndexStatus | null;
	indexer?: SearchAdminIndexerStatus | null;
	datasource?: SearchAdminDataSourceStatus | null;
	skillsets?: Array<SearchAdminSkillStatus> | null;
}
