/**
 * Agravity OpenAPI Documentation - Public Functions
 *
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchAdminStatistics } from './searchAdminStatistics.pub.agravity';

export interface SearchAdminIndexStatus {
	name?: string | null;
	status?: string | null;
	statistics?: SearchAdminStatistics | null;
}
