/**
 * Agravity OpenAPI Documentation - Public Functions
 *
 * Contact: support@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionType } from './collectionType.pub.agravity';
import { PermissionEntity } from './permissionEntity.pub.agravity';

export interface Workspace {
	id?: string | null;
	entity_type?: string | null;
	name?: string | null;
	collection_types?: Array<CollectionType> | null;
	translations?: { [key: string]: { [key: string]: any } } | null;
	order?: number | null;
	permissions?: Array<PermissionEntity> | null;
	description?: string | null;
	add_properties?: { [key: string]: any } | null;
	status?: string | null;
	created_date?: string | null;
	created_by?: string | null;
	modified_date?: string | null;
	modified_by?: string | null;
	pk?: string | null;
	_etag?: string | null;
}
