/**
 * Agravity OpenAPI Documentation - Public Functions
 * <h1>Agravity API Reference</h1>This is the public API description of Agravity GmbH.<br/><h2>Resources</h2><ul> <li>Collection type management</li> <li>Collections management</li> <li>Assets management</li> <li>Assets operations</li> <li>Assets publishing</li> <li>Collection Sharing (consume share)</li> <li>Secure Upload (validate + upload file)</li> <li>Download ZIP</li> <li>Search</li> <li>General management</li></ul><h2> Operations</h2>Agravity API performs the following operations:<ul> <li>List / get single collection types</li> <li>List / get single collections</li> <li>List / get single  assets</li> <li>Operations on assets like: blobs, rotate, resize, similar, collections, customfields, download</li> <li>List / get single published asset</li> <li>Search for assets or collections</li> <li>Get version of deployment</li></ul><br/><b>API key is needed to access these endpoints.</b><br/><br/>Copyright © Agravity GmbH 2024. All Rights Reserved
 *
 * The version of the OpenAPI document: 7.2.1
 * Contact: office@agravity.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec } from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

import { AgravityErrorResponse } from '../model/models';
import { SearchFacet } from '../model/models';
import { SearchResult } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { AgravityPublicConfiguration } from '../configuration';

@Injectable({
	providedIn: 'root'
})
export class PublicSearchManagementService {
	protected basePath = 'http://localhost:7072/api';
	public defaultHeaders = new HttpHeaders();
	public configuration = new AgravityPublicConfiguration();
	public encoder: HttpParameterCodec;

	constructor(
		protected httpClient: HttpClient,
		@Optional() @Inject(BASE_PATH) basePath: string,
		@Optional() configuration: AgravityPublicConfiguration
	) {
		if (configuration) {
			this.configuration = configuration;
		}
		if (typeof this.configuration.basePath !== 'string') {
			if (typeof basePath !== 'string') {
				basePath = this.basePath;
			}
			this.configuration.basePath = basePath;
		}
		this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
	}

	private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
		if (typeof value === 'object' && value instanceof Date === false) {
			httpParams = this.addToHttpParamsRecursive(httpParams, value);
		} else {
			httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
		}
		return httpParams;
	}

	private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
		if (value == null) {
			return httpParams;
		}

		if (typeof value === 'object') {
			if (Array.isArray(value)) {
				(value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
			} else if (value instanceof Date) {
				if (key != null) {
					httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
				} else {
					throw Error('key may not be null if value is Date');
				}
			} else {
				Object.keys(value).forEach((k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k)));
			}
		} else if (key != null) {
			httpParams = httpParams.append(key, value);
		} else {
			throw Error('key may not be null if value is not object or array');
		}
		return httpParams;
	}

	/**
	 * This endpoint returns one facette based on the search parameters.
	 * @param name The name of the facette.
	 * @param s The search string which should be found.
	 * @param collectiontypeid Limits the result on all collections from the given collectiontypeid parameter.
	 * @param collectionid Limits the result on collection id (and siblings). Will be overwritten by collectiontypeid parameter.
	 * @param mode Two modes supported: \&quot;any\&quot; or \&quot;all\&quot; search terms should be applied. (Only if Azure Search is enabled)
	 * @param filter Key value filter for filterable strings and string collections separated by special \&#39;,,,\&#39;. For date or numbers \&quot;&lt;\&quot;, \&quot;&#x3D;\&quot; and \&quot;&gt;\&quot; are possible. Mode influences AND (all) and OR (any) of all filters. Multiple filters are separated by semicolons. (Only if Azure Search is enabled)
	 * @param ids Comma separated values list with all ids which should be returned.
	 * @param portalId If the search should be redirected to a specific portal.
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public httpGetSearchFacetteByName(
		name: string,
		s: string,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		filter?: string,
		ids?: string,
		portalId?: string,
		observe?: 'body',
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<SearchFacet>;
	public httpGetSearchFacetteByName(
		name: string,
		s: string,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		filter?: string,
		ids?: string,
		portalId?: string,
		observe?: 'response',
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<HttpResponse<SearchFacet>>;
	public httpGetSearchFacetteByName(
		name: string,
		s: string,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		filter?: string,
		ids?: string,
		portalId?: string,
		observe?: 'events',
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<HttpEvent<SearchFacet>>;
	public httpGetSearchFacetteByName(
		name: string,
		s: string,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		filter?: string,
		ids?: string,
		portalId?: string,
		observe: any = 'body',
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<any> {
		if (name === null || name === undefined) {
			throw new Error('Required parameter name was null or undefined when calling httpGetSearchFacetteByName.');
		}
		if (s === null || s === undefined) {
			throw new Error('Required parameter s was null or undefined when calling httpGetSearchFacetteByName.');
		}

		let queryParameters = new HttpParams({ encoder: this.encoder });
		if (name !== undefined && name !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>name, 'name');
		}
		if (s !== undefined && s !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>s, 's');
		}
		if (collectiontypeid !== undefined && collectiontypeid !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>collectiontypeid, 'collectiontypeid');
		}
		if (collectionid !== undefined && collectionid !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>collectionid, 'collectionid');
		}
		if (mode !== undefined && mode !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>mode, 'mode');
		}
		if (filter !== undefined && filter !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>filter, 'filter');
		}
		if (ids !== undefined && ids !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>ids, 'ids');
		}
		if (portalId !== undefined && portalId !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>portalId, 'portal_id');
		}

		let headers = this.defaultHeaders;

		let credential: string | undefined;
		// authentication (function_key) required
		credential = this.configuration.lookupCredential('function_key');
		if (credential) {
			headers = headers.set('x-functions-key', credential);
		}

		let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (httpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ['application/json'];
			httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (httpHeaderAcceptSelected !== undefined) {
			headers = headers.set('Accept', httpHeaderAcceptSelected);
		}

		let responseType_: 'text' | 'json' = 'json';
		if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
			responseType_ = 'text';
		}

		return this.httpClient.get<SearchFacet>(`${this.configuration.basePath}/search/facette`, {
			params: queryParameters,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: headers,
			observe: observe,
			reportProgress: reportProgress
		});
	}

	/**
	 * This endpoint returns a configured max amount of results for search terms.
	 * @param s The search string which should be found.
	 * @param limit How many results should be returend. 0 is backend configuration limit.
	 * @param skip (default: 0) - Used for paging - how many items should be skipped before next limit results will be fetched.
	 * @param collectiontypeid Limits the result on all collections from the given collectiontypeid parameter.
	 * @param collectionid Limits the result on collection id (and siblings). Will be overwritten by collectiontypeid parameter.
	 * @param mode Two modes supported: \&quot;any\&quot; or \&quot;all\&quot; search terms should be applied. (Only if Azure Search is enabled)
	 * @param expose This will expose the thumbnail asset blob incl. URL with SAS Token.
	 * @param filter Colon separated key value filter for filterable strings and string collections. For date or numbers \&quot;&lt;\&quot;, \&quot;&#x3D;\&quot; and \&quot;&gt;\&quot; are possible. Mode influences AND (all) and OR (any) of all filters. Multiple filters are separated by semicolons. (Only if Azure Search is enabled)
	 * @param orderby Sortable fields can be used. For descendant sorting use leading \&quot;!\&quot;. (Only if Azure Search is enabled)
	 * @param ids Comma separated values list with all ids which should be returned.
	 * @param portalId If the search should be redirected to a specific portal.
	 * @param translations When default language should be returned and the translation dictionary is delivered. (Ignores the \&quot;Accept-Language\&quot; header)
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public httpGlobalSearch(
		s: string,
		limit?: number,
		skip?: number,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		expose?: boolean,
		filter?: string,
		orderby?: string,
		ids?: string,
		portalId?: string,
		translations?: boolean,
		observe?: 'body',
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<SearchResult>;
	public httpGlobalSearch(
		s: string,
		limit?: number,
		skip?: number,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		expose?: boolean,
		filter?: string,
		orderby?: string,
		ids?: string,
		portalId?: string,
		translations?: boolean,
		observe?: 'response',
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<HttpResponse<SearchResult>>;
	public httpGlobalSearch(
		s: string,
		limit?: number,
		skip?: number,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		expose?: boolean,
		filter?: string,
		orderby?: string,
		ids?: string,
		portalId?: string,
		translations?: boolean,
		observe?: 'events',
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<HttpEvent<SearchResult>>;
	public httpGlobalSearch(
		s: string,
		limit?: number,
		skip?: number,
		collectiontypeid?: string,
		collectionid?: string,
		mode?: string,
		expose?: boolean,
		filter?: string,
		orderby?: string,
		ids?: string,
		portalId?: string,
		translations?: boolean,
		observe: any = 'body',
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: 'application/json' }
	): Observable<any> {
		if (s === null || s === undefined) {
			throw new Error('Required parameter s was null or undefined when calling httpGlobalSearch.');
		}

		let queryParameters = new HttpParams({ encoder: this.encoder });
		if (s !== undefined && s !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>s, 's');
		}
		if (limit !== undefined && limit !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>limit, 'limit');
		}
		if (skip !== undefined && skip !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>skip, 'skip');
		}
		if (collectiontypeid !== undefined && collectiontypeid !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>collectiontypeid, 'collectiontypeid');
		}
		if (collectionid !== undefined && collectionid !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>collectionid, 'collectionid');
		}
		if (mode !== undefined && mode !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>mode, 'mode');
		}
		if (expose !== undefined && expose !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>expose, 'expose');
		}
		if (filter !== undefined && filter !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>filter, 'filter');
		}
		if (orderby !== undefined && orderby !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>orderby, 'orderby');
		}
		if (ids !== undefined && ids !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>ids, 'ids');
		}
		if (portalId !== undefined && portalId !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>portalId, 'portal_id');
		}
		if (translations !== undefined && translations !== null) {
			queryParameters = this.addToHttpParams(queryParameters, <any>translations, 'translations');
		}

		let headers = this.defaultHeaders;

		let credential: string | undefined;
		// authentication (function_key) required
		credential = this.configuration.lookupCredential('function_key');
		if (credential) {
			headers = headers.set('x-functions-key', credential);
		}

		let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (httpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ['application/json'];
			httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (httpHeaderAcceptSelected !== undefined) {
			headers = headers.set('Accept', httpHeaderAcceptSelected);
		}

		let responseType_: 'text' | 'json' = 'json';
		if (httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
			responseType_ = 'text';
		}

		return this.httpClient.get<SearchResult>(`${this.configuration.basePath}/search`, {
			params: queryParameters,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: headers,
			observe: observe,
			reportProgress: reportProgress
		});
	}
}
